[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

# Karma 3 patch. 50% chance to spawn a Common Eternal Joker whenever you obtain a Joker.
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = '''if not self.config.center.discovered then
        discover_card(self.config.center)
    end'''
position = "before"
payload = '''
for _, v in ipairs(G.GAME.applied_stakes) do
 if SMODS.stake_from_index(v) == "stake_rw_companion" and G.jokers.config.card_limit > #G.jokers.cards then
	if self.ability.set == 'Joker' and not self.ability.eternal and not self.ability.enemy == true then
	
if SMODS.pseudorandom_probability(self, 'newjoker', 1, 2, "newjoke") and #G.jokers.cards < G.jokers.config.card_limit then

 G.E_MANAGER:add_event(Event({
 trigger = "after",
 delay = 2,
    func = function() 
SMODS.add_card({ set = "Joker", area = G.jokers, rarity = "Common", stickers = {'eternal'}, force_stickers = true})
	print('card added')
        return true 
    end,
	
}))
   end
   
	end
  end
end
'''
match_indent = true